# Generated by Django 2.2.11 on 2020-03-21 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outros', '0001_initial'),
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='cidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='cidade', to='outros.Cidade'),
            preserve_default=False,
        ),
    ]
