# Generated by Django 2.2.11 on 2020-03-29 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='limite_produto',
        ),
    ]
