# Generated by Django 2.2.11 on 2020-03-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_empresa_cidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='sexo',
            field=models.IntegerField(choices=[(0, 'Masculino'), (1, 'Feminino'), (2, 'Outro')], default=1, verbose_name='Sexo'),
            preserve_default=False,
        ),
    ]
