# Generated by Django 2.2.11 on 2020-03-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0003_cliente_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.BigIntegerField(unique=True, verbose_name='Telefone'),
        ),
    ]
