# Generated by Django 2.2.11 on 2020-03-29 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Categoria de Produtos',
                'verbose_name_plural': 'Categorias de Produtos',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.CharField(help_text='Por exemplo, Rua Júlio Rosa', max_length=50, verbose_name='Endereço')),
                ('numero', models.IntegerField(help_text='Se não houver número, digite 0', verbose_name='Número')),
                ('complemento', models.CharField(blank=True, help_text='Por exemplo, apto 402', max_length=50, null=True)),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='Data/Hora do Pedido')),
                ('horario_entrega', models.CharField(help_text='Descreva os horários disponíveis para você receber os produtos.', max_length=30, verbose_name='Horário de entrega')),
                ('observacao_cliente', models.TextField(blank=True, null=True, verbose_name='Observação do Cliente')),
                ('observacao_funcionario', models.TextField(blank=True, null=True, verbose_name='Observação do Funcionário')),
                ('impresso', models.BooleanField(default=False)),
                ('pdf_gerado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='StatusPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Situação dos Pedidos',
                'verbose_name_plural': 'Situações dos Pedidos',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='StatusProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Situação dos Produtos',
                'verbose_name_plural': 'Situações dos Produtos',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categoria_produto', to='pedidos.CategoriaProduto')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='PedidoProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.CharField(max_length=30)),
                ('valor_unitario', models.FloatField()),
                ('valor_total', models.FloatField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='pp_pedido', to='pedidos.Pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_query_name='pp_produto', to='pedidos.Produto')),
            ],
            options={
                'verbose_name': 'Produtos do pedido',
                'ordering': ['produto'],
                'verbose_name_plural': 'Produtos dos pedidos',
            },
        ),
    ]
