# Generated by Django 2.2.11 on 2020-03-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_auto_20200321_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='observacao_cliente',
            field=models.TextField(blank=True, null=True, verbose_name='Observação do Cliente'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='observacao_funcionario',
            field=models.TextField(blank=True, null=True, verbose_name='Observação do Funcionário'),
        ),
    ]
