# Generated by Django 2.2.11 on 2020-03-29 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_auto_20200329_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='situacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categoria_produto', to='pedidos.StatusProduto', verbose_name='Situação'),
        ),
    ]
