# Generated by Django 2.2.11 on 2020-03-29 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_produto_situacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='situacao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='categoria_produto', to='pedidos.StatusProduto', verbose_name='Situação'),
            preserve_default=False,
        ),
    ]
