# Generated by Django 2.2.11 on 2020-03-21 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_auto_20200321_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=30, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Situação do Pedidos',
                'ordering': ['descricao'],
                'verbose_name_plural': 'Situações dos Pedidos',
            },
        ),
        migrations.AlterField(
            model_name='endereco',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido', to='pedidos.Pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='status', to='pedidos.StatusPedido', verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='pedidoproduto',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='pp_pedido', to='pedidos.Pedido'),
        ),
    ]
