# Generated by Django 2.2.11 on 2020-03-29 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_auto_20200329_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='descricao',
        ),
        migrations.AddField(
            model_name='endereco',
            name='referencia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ponto de Referência'),
        ),
    ]
