# Generated by Django 2.2.11 on 2020-03-29 21:14

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoEmpresa',
            fields=[
            ],
            options={
                'verbose_name': 'Produto da empresa',
                'ordering': ['descricao'],
                'constraints': [],
                'verbose_name_plural': 'Produtos da empresa',
                'proxy': True,
                'indexes': [],
            },
            bases=('pedidos.produto',),
        ),
    ]
